---
- name: Disable swap for current session
  command: swapoff -a
  become: true

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- name: Install packages
  vars:
    package_name:
      - zsh
      - git
      - git-lfs
      - fish
      - neovim
      - zip
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true

- name: Install var-crash-nuke helper
  become: true
  copy:
    src: var-crash-nuke.sh
    dest: /usr/local/sbin/var-crash-nuke.sh
    owner: root
    group: root
    mode: '0755'

- name: Install tmp-cleaner helper
  become: true
  copy:
    src: tmp-cleaner.sh
    dest: /usr/local/sbin/tmp-cleaner.sh
    owner: root
    group: root
    mode: '0755'

- name: Install cleanup runner
  become: true
  copy:
    src: cleanup-runner.sh
    dest: /usr/local/sbin/cleanup-runner.sh
    owner: root
    group: root
    mode: '0755'

- name: Ensure cleanup runs periodically
  become: true
  cron:
    name: tmp directory cleanup
    minute: "*/5"
    user: ubuntu
    job: "/usr/local/sbin/cleanup-runner.sh"

- name: Remove old tmp-duster script
  become: true
  file:
    path: /usr/local/sbin/tmp-duster.sh
    state: absent

- name: Install new healthchecks
  become: true
  block:
    - name: Ensure healthchecks directory exists
      file:
        path: /opt/oci-hpc/healthchecks
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy healthcheck scripts
      copy:
        src: "{{ item }}"
        dest: "/opt/oci-hpc/healthchecks/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      loop:
        - check_gpu_setup.py
        - xid_checker.py
  
