---
- name: Install iptables services for persistence
  vars: 
    package_name: 
      - iptables-services
  include_role: 
    name: safe_yum

- name: Start iptables services
  ansible.builtin.service:
    name: "iptables"
    enabled: true
    state: started

- name: Setup iptables chains and rules for billing
  become: true
  block:
    # Ansible 2.9 doesn't allow for chain management so we need to create the chain ourselves
    - name: Create user-defined chain
      shell: iptables -N USER_TRAFFIC
      ignore_errors: true

    - name: Insert USER_TRAFFIC chain to OUTPUT
      ansible.builtin.iptables:
        chain: OUTPUT
        jump: USER_TRAFFIC
        action: insert

    - name: Append rule to USER_TRAFFIC chain
      ansible.builtin.iptables:
        table: filter
        chain: USER_TRAFFIC
        destination: 172.16.0.0/21
        jump: RETURN
        action: append

    # Save the rules
    - name: Save iptables rules
      shell: iptables-save | tee /etc/sysconfig/iptables

    - name: Save ip6tables rules
      shell: ip6tables-save | tee /etc/sysconfig/ip6tables
  when: billing | default(false) | bool