- name: Download the goslmailer release
  include: download_goslmailer.yml

- name: Perform Required File operations for goslmailer
  include: goslmailer_file_ops.yml

- name: Install strigger scripts
  include: admin_notifications_install.yml

- name: Delete /tmp/Goslmailer directory
  file:
    path: /tmp/goslmailer
    state: absent