- name: Download the goslmailer release
  include_tasks: download_goslmailer.yml

- name: Perform Required File operations for goslmailer
  include_tasks: goslmailer_file_ops.yml

- name: Install strigger scripts
  include_tasks: admin_notifications_install.yml

- name: Delete /tmp/Goslmailer directory
  file:
    path: /tmp/goslmailer
    state: absent