---
- name: Install gflags
  vars: 
    package_name: 
      - libgflags-dev
      - libgflags2.2
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true

- name: Install glog
  vars: 
    package_name: 
      - libglog0v5
      - libglog-dev
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true

- name: Install go
  vars: 
    package_name:
      - golang
      - golang-go
      - golang-doc
      - vim-gocomplete
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true

- name: Install gcc
  vars: 
    package_name: 
      - gcc
      - g++
      - gdb
      - gfortran
      - gcc-plugin-dev
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true

- name: Install git-lfs
  vars:
    package_name:
      - git-lfs
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true

- name: Install openGL/Mesa
  vars:
    package_name:
      - libosmesa6
      - libosmesa6-dev
      - libglfw3
      - libglfw3-dev
      - libgl1-mesa-glx
      - libgl1-mesa-dev
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true

- name: Install libaio for asynchronous I/O
  vars:
    package_name:
      - libaio-dev
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true