---

- hosts: all
  become: true
  tasks:
    - name: Install ssh key for root access
      authorized_key:
        user: root
        key: "{{ lookup('file', '/home/opc/.ssh/root_key.pub') }}"
        state: present
