- name: Uninstall goslmailer
  hosts: bastion, slurm_backup
  gather_facts: false
  become: true
  tasks:
    - name: Remove goslmailer binary
      file:
        path: /bin/goslmailer
        state: absent

    - name: Remove gobler binary
      file:
        path: /bin/gobler
        state: absent

    - name: Remove slack directory
      file:
        path: /var/spool/slack
        state: absent

    - name: Remove notification_templates directory
      file:
        path: /etc/slurm/notification_templates
        state: absent

    - name: Remove goslmailer.log file
      file:
        path: /data/spool/goslmailer.log
        state: absent

    - name: Remove goslmailer.conf file
      file:
        path: /etc/slurm/goslmailer.conf
        state: absent

    - name: Remove gobler.conf file
      file:
        path: /etc/slurm/gobler.conf
        state: absent
    
    - name: Stop gobler service
      systemd:
        name: gobler
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove gobler.service file
      file:
        path: /etc/systemd/system/gobler.service
        state: absent

    - name: Remove triggers directory
      file:
        path: /etc/slurm/triggers
        state: absent

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

- name: Remove striggers for admin notifications
  hosts: bastion
  gather_facts: false
  become: true
  vars:
  tasks:
    - name: Run strigger --get and capture output
      command: strigger --get
      register: command_output

    - name: Extract IDs from output
      set_fact:
        trigger_ids: "{{ (command_output.stdout | regex_findall('^\\s*(\\d+).*\\/etc\\/slurm\\/triggers\\/admin_notifications\\/.*$', multiline=True)) }}"

    - name: Run strigger --clear on IDs
      command: strigger --clear --id "{{ item }}"
      ignore_errors: true
      become_user: slurm
      loop: "{{ trigger_ids }}"
      loop_control:
        loop_var: item
