---
- name: Update /etc/issue.net file
  hosts: controller
  become: true  # Ensure you have administrative privileges
  tasks:
    - name: Add warning message to /etc/issue.net
      lineinfile:
        path: /etc/issue.net
        line: 'Warning: Passwordless SSH is enabled for root user.'
        create: yes  # Create the file if it does not exist
        state: present

- name: Setup passwordless SSH for root user
  hosts: all
  become: true
  tasks:
    - name: Ensure the SSH directory exists
      file:
        path: "/root/.ssh"
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Read the public key from the file
      slurp:
        src: "/home/{{ ansible_user }}/.ssh/root.pub"
      register: public_key

    - name: Convert the public key to a string
      set_fact:
        pubkey_content: "{{ public_key['content'] | b64decode }}"

    - name: Append the public key to the authorized_keys file
      lineinfile:
        path: "/root/.ssh/authorized_keys"
        line: "{{ pubkey_content }}"
        create: yes
        owner: root
        group: root
        mode: '0600'
        state: present

    - name: Copy the private key to the SSH directory
      copy:
        src: "/home/{{ ansible_user }}/.ssh/root"
        dest: "/root/.ssh/id_rsa"
        owner: root
        group: root
        mode: '0600'

