---
- name: Disable passwordless SSH for root user
  hosts: all
  become: true
  tasks:
    - name: Ensure the SSH directory exists
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0700'
      ignore_errors: true

    - name: Ensure the authorized_keys file exists
      file:
        path: /root/.ssh/authorized_keys
        state: touch
        owner: root
        group: root
        mode: '0600'
      ignore_errors: true

    - name: Remove the root's public key from the authorized_keys file
      lineinfile:
        path: /root/.ssh/authorized_keys
        state: absent
        line: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/root.pub') }}"
      ignore_errors: true

    - name: Remove the private key file
      file:
        path: "/root/.ssh/root"
        state: absent
      ignore_errors: true

    - name: Ensure there is at least one newline at the end of the file
      lineinfile:
        path: "/root/.ssh/authorized_keys"
        line: ''
        create: no
        insertafter: EOF

    - name: Remove extra newlines from the end of the file
      command: sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' /root/.ssh/authorized_keys
      args:
        warn: false

- name: Remove specific warning from /etc/issue.net file
  hosts: controller
  become: true  # Ensure you have administrative privileges
  tasks:
    - name: Remove warning message from /etc/issue.net
      lineinfile:
        path: /etc/issue.net
        line: 'Warning: Passwordless SSH is enabled for root user.'
        state: absent