---

- hosts: all
  become: true
  gather_facts: false
  vars:
    ssh_key: "{{ lookup('file', '/mnt/fss/home/opc/.ssh/root_key.pub') }}"
  tasks:
    - name: Install ssh key for root access
      authorized_key:
        user: root
        key: "{{ ssh_key }}"
        state: present