- hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "Gathering facts"
- hosts: compute, slurm_backup
  gather_facts: true
  vars:
    destroy: false
    initial: false
    download_path: "/tmp"
    enroot_top_path: "{{ nvme_path }}/enroot/"
  vars_files:
    - "/opt/oci-hpc/conf/queues.conf"
  tasks:
    - include_role: 
        name: slurm
      when: slurm|default(false)|bool